import '../../design_system/design_system.dart';
import 'token_showcase_widgets.dart';

class SemanticColorGroup {
  const SemanticColorGroup({required this.title, required this.entries});

  final String title;
  final List<ColorEntry> entries;
}

List<SemanticColorGroup> semanticColorGroups(SemanticColors c) {
  return [
    SemanticColorGroup(
      title: 'Background',
      entries: [
        (name: 'backgroundPrimary', color: c.backgroundPrimary),
        (name: 'backgroundSecondary', color: c.backgroundSecondary),
        (name: 'backgroundTertiary', color: c.backgroundTertiary),
        (name: 'backgroundDark', color: c.backgroundDark),
        (name: 'backgroundBlack', color: c.backgroundBlack),
        (name: 'backgroundBlackSecondary', color: c.backgroundBlackSecondary),
        (name: 'backgroundDisable1', color: c.backgroundDisable1),
        (name: 'backgroundDisable2', color: c.backgroundDisable2),
        (name: 'backgroundDisable3', color: c.backgroundDisable3),
        (name: 'backgroundBrandPrimary1', color: c.backgroundBrandPrimary1),
        (name: 'backgroundBrandPrimary2', color: c.backgroundBrandPrimary2),
        (name: 'backgroundBrandPrimary3', color: c.backgroundBrandPrimary3),
        (name: 'backgroundBrandPrimary4', color: c.backgroundBrandPrimary4),
        (name: 'backgroundBrandPrimary5', color: c.backgroundBrandPrimary5),
        (name: 'backgroundBrandSecondary1', color: c.backgroundBrandSecondary1),
        (name: 'backgroundBrandSecondary2', color: c.backgroundBrandSecondary2),
        (name: 'backgroundBrandSecondary3', color: c.backgroundBrandSecondary3),
        (name: 'backgroundBrandSecondary4', color: c.backgroundBrandSecondary4),
        (name: 'backgroundBrandSecondary5', color: c.backgroundBrandSecondary5),
        (name: 'backgroundBrandTertiary1', color: c.backgroundBrandTertiary1),
        (name: 'backgroundBrandTertiary2', color: c.backgroundBrandTertiary2),
        (name: 'backgroundBrandTertiary3', color: c.backgroundBrandTertiary3),
        (name: 'backgroundBrandTertiary4', color: c.backgroundBrandTertiary4),
        (name: 'backgroundBrandQuaternary1', color: c.backgroundBrandQuaternary1),
        (name: 'backgroundBrandQuaternary2', color: c.backgroundBrandQuaternary2),
        (name: 'backgroundBrandQuaternary3', color: c.backgroundBrandQuaternary3),
        (name: 'backgroundBrandQuaternary4', color: c.backgroundBrandQuaternary4),
        (name: 'backgroundBrandQuaternary5', color: c.backgroundBrandQuaternary5),
        (name: 'backgroundErrorPrimary', color: c.backgroundErrorPrimary),
        (name: 'backgroundErrorSecondary', color: c.backgroundErrorSecondary),
        (name: 'backgroundErrorTertiary', color: c.backgroundErrorTertiary),
        (name: 'backgroundSuccessPrimary', color: c.backgroundSuccessPrimary),
        (name: 'backgroundSuccessSecondary', color: c.backgroundSuccessSecondary),
        (name: 'backgroundSuccessTertiary', color: c.backgroundSuccessTertiary),
        (name: 'backgroundSuccessQuaternary', color: c.backgroundSuccessQuaternary),
        (name: 'backgroundWarningPrimary', color: c.backgroundWarningPrimary),
        (name: 'backgroundWarningSecondary', color: c.backgroundWarningSecondary),
        (name: 'backgroundWarningTertiary', color: c.backgroundWarningTertiary),
      ],
    ),
    SemanticColorGroup(
      title: 'Border',
      entries: [
        (name: 'borderPrimary', color: c.borderPrimary),
        (name: 'borderSecondary', color: c.borderSecondary),
        (name: 'borderTertiary', color: c.borderTertiary),
        (name: 'borderQuaternary', color: c.borderQuaternary),
        (name: 'borderQuaternary2', color: c.borderQuaternary2),
        (name: 'borderBrandPrimary1', color: c.borderBrandPrimary1),
        (name: 'borderBrandPrimary2', color: c.borderBrandPrimary2),
        (name: 'borderBrandPrimary3', color: c.borderBrandPrimary3),
        (name: 'borderBrandPrimary4', color: c.borderBrandPrimary4),
        (name: 'borderBrandSecondary1', color: c.borderBrandSecondary1),
        (name: 'borderBrandSecondary2', color: c.borderBrandSecondary2),
        (name: 'borderBrandSecondary3', color: c.borderBrandSecondary3),
        (name: 'borderBrandSecondary4', color: c.borderBrandSecondary4),
        (name: 'borderBrandTertiary', color: c.borderBrandTertiary),
        (name: 'borderDisable1', color: c.borderDisable1),
        (name: 'borderDisable2', color: c.borderDisable2),
        (name: 'borderError1', color: c.borderError1),
        (name: 'borderError2', color: c.borderError2),
        (name: 'borderError3', color: c.borderError3),
        (name: 'borderSuccess', color: c.borderSuccess),
        (name: 'borderWarning', color: c.borderWarning),
      ],
    ),
    SemanticColorGroup(
      title: 'Text',
      entries: [
        (name: 'textPrimary', color: c.textPrimary),
        (name: 'textPrimary2', color: c.textPrimary2),
        (name: 'textPrimary3', color: c.textPrimary3),
        (name: 'textPrimary4', color: c.textPrimary4),
        (name: 'textSecondary', color: c.textSecondary),
        (name: 'textTertiary', color: c.textTertiary),
        (name: 'textQuaternary', color: c.textQuaternary),
        (name: 'textQuaternary2', color: c.textQuaternary2),
        (name: 'textWhite', color: c.textWhite),
        (name: 'textDisable1', color: c.textDisable1),
        (name: 'textDisable2', color: c.textDisable2),
        (name: 'textDisable3', color: c.textDisable3),
        (name: 'textDisable4', color: c.textDisable4),
        (name: 'textError', color: c.textError),
        (name: 'textSuccess', color: c.textSuccess),
        (name: 'textBrandPrimary1', color: c.textBrandPrimary1),
        (name: 'textBrandPrimary2', color: c.textBrandPrimary2),
        (name: 'textBrandPrimary3', color: c.textBrandPrimary3),
        (name: 'textBrandPrimary4', color: c.textBrandPrimary4),
        (name: 'textBrandSecondary1', color: c.textBrandSecondary1),
        (name: 'textBrandSecondary2', color: c.textBrandSecondary2),
        (name: 'textBrandSecondary3', color: c.textBrandSecondary3),
        (name: 'textBrandSecondary4', color: c.textBrandSecondary4),
        (name: 'textBrandTertiary1', color: c.textBrandTertiary1),
        (name: 'textBrandTertiary2', color: c.textBrandTertiary2),
        (name: 'hyperlinkDefault', color: c.hyperlinkDefault),
        (name: 'hyperlinkHover', color: c.hyperlinkHover),
        (name: 'hyperlinkPressed', color: c.hyperlinkPressed),
        (name: 'hyperlinkLoading', color: c.hyperlinkLoading),
        (name: 'hyperlinkDisabled', color: c.hyperlinkDisabled),
      ],
    ),
    SemanticColorGroup(
      title: 'Icon',
      entries: [
        (name: 'iconBrandPrimary1', color: c.iconBrandPrimary1),
        (name: 'iconBrandPrimary2', color: c.iconBrandPrimary2),
        (name: 'iconBrandPrimary3', color: c.iconBrandPrimary3),
        (name: 'iconBrandPrimary4', color: c.iconBrandPrimary4),
        (name: 'iconBrandSecondary1', color: c.iconBrandSecondary1),
        (name: 'iconBrandSecondary2', color: c.iconBrandSecondary2),
        (name: 'iconBrandSecondary3', color: c.iconBrandSecondary3),
        (name: 'iconBrandSecondary4', color: c.iconBrandSecondary4),
        (name: 'iconNeutral1', color: c.iconNeutral1),
        (name: 'iconNeutral2', color: c.iconNeutral2),
        (name: 'iconNeutral3', color: c.iconNeutral3),
        (name: 'iconNeutral4', color: c.iconNeutral4),
        (name: 'iconNeutral5', color: c.iconNeutral5),
        (name: 'iconNeutral6', color: c.iconNeutral6),
        (name: 'iconDisable1', color: c.iconDisable1),
        (name: 'iconDisable2', color: c.iconDisable2),
        (name: 'iconDisable3', color: c.iconDisable3),
        (name: 'iconDisable4', color: c.iconDisable4),
        (name: 'iconError', color: c.iconError),
        (name: 'iconSuccess', color: c.iconSuccess),
        (name: 'iconWarning', color: c.iconWarning),
        (name: 'iconWhite', color: c.iconWhite),
      ],
    ),
    SemanticColorGroup(
      title: 'Chart',
      entries: [
        for (var i = 1; i <= 20; i++)
          (
            name: 'chart$i',
            color: switch (i) {
              1 => c.chart1,
              2 => c.chart2,
              3 => c.chart3,
              4 => c.chart4,
              5 => c.chart5,
              6 => c.chart6,
              7 => c.chart7,
              8 => c.chart8,
              9 => c.chart9,
              10 => c.chart10,
              11 => c.chart11,
              12 => c.chart12,
              13 => c.chart13,
              14 => c.chart14,
              15 => c.chart15,
              16 => c.chart16,
              17 => c.chart17,
              18 => c.chart18,
              19 => c.chart19,
              _ => c.chart20,
            },
          ),
      ],
    ),
    SemanticColorGroup(
      title: 'Other',
      entries: [
        (name: 'dividerPrimary', color: c.dividerPrimary),
        (name: 'overlayPrimary', color: c.overlayPrimary),
        (name: 'shadow1', color: c.shadow1),
        (name: 'shadow2', color: c.shadow2),
        (name: 'shadow3', color: c.shadow3),
        (name: 'shadow4', color: c.shadow4),
        (name: 'shadow5', color: c.shadow5),
        (name: 'skeletonPrimary', color: c.skeletonPrimary),
        (name: 'skeletonSecondary', color: c.skeletonSecondary),
        (name: 'blur1', color: c.blur1),
      ],
    ),
  ];
}
